name: Check repo

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  cdxgen:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04 
      
    steps:
      - name: Install packages & cdxgen
        run: |
          apt-get update
          apt-get install -y wget apt-transport-https gnupg lsb-release python3 python3-pip python-is-python3
          wget -q https://github.com/cdxgen/cdxgen/releases/download/v12.1.1/cdxgen-linux-amd64 -O /bin/cdxgen
          chmod +x /bin/cdxgen
        
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Cdxgen
        run: |
          cdxgen -o /tmp/cdxgen.json "$GITHUB_WORKSPACE"          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cdxgen-sbom
          path: /tmp/cdxgen.json
          retention-days: 30 

  trivy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04 
      
    steps:
      - name: Install packages & trivy
        run: |
          apt-get update
          apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/trivy.list
          apt-get update
          apt-get install trivy
        
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Trivy
        run: |
          trivy fs --detection-priority comprehensive --format cyclonedx --output /tmp/sbom.json "$GITHUB_WORKSPACE"
          trivy fs --detection-priority comprehensive --format sarif --output /tmp/trivy.sarif "$GITHUB_WORKSPACE"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom
          path: /tmp/sbom.json
          retention-days: 30
            
      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: '/tmp/trivy.sarif'
      
  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04 
      
    steps:
      - name: Install packages & gitleaks
        run: |
          apt-get update
          apt-get install -y wget apt-transport-https gnupg lsb-release tar
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.29.0/gitleaks_8.29.0_linux_x64.tar.gz
          tar -xf gitleaks_8.29.0_linux_x64.tar.gz
          mv gitleaks /bin/        
          
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Gitleaks
        run: |
          gitleaks dir -f sarif -r /tmp/gitleaks.json --exit-code 0 "$GITHUB_WORKSPACE"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-sarif
          path: /tmp/gitleaks.json
          retention-days: 30      
